from QtModularUiPack.ModularApplications.ToolsFrames.experiment_frame import ExperimentFrame
from QtModularUiPack.ModularApplications.ToolsFrames.hello_world_frame import HelloWorldFrame
from QtModularUiPack.ModularApplications.ToolsFrames.tool_command_frame import ToolCommandFrame
